### ISSUE TITLE
Retire cards due after a certain date

### ISSUE THREAD

**Issue by StookDog** [mass-immersion-approach/MIARetirementAddon#11]
**New feature request:** 
Retire cards due after a certain date

**New feature details:**
This addon is great. I think it would be helpful if you could add a feature that would trigger the retire option once the card's due date is after a certain customizable date (per deck option group, if possible). 

Eg if you have a test on 07/01/2020 and you just reviewed a card that will be now due on 07/02/2020 of after it will be retired (tagged, moved, suspended, whatever you have selected).

Thanks!

**Comment by FearrMe** [comment]
How's this different from reviewing a deck until the test, then after the test suspending all cards in the deck?

**Comment by KieranBrannigan** [comment]
As @FearrMe said, I think this functionality can be achieved by making a separate deck where you put your test content. After your test, you can simply suspend/delete the deck. 

If you want to review these new cards with your main sentence deck, then you could put your test deck and you main deck in a deck-group. Then review the deck group to review them together. Just make sure the options of the parent deck and child decks are set up properly to make sure the reviews aren't limited etc. You can check out the [anki docs](https://docs.ankiweb.net/#/) for info.
