### ISSUE TITLE
Bug: All cloze notes of one card tagged when only one is ready to retire

### ISSUE THREAD

**Issue by StookDog** [mass-immersion-approach/MIARetirementAddon#12]
Pretty self explanatory. I have many cards that have multiple cloze fields and when one of those notes reaches the retirement age the addon retires the entire card including the other notes. This is an issue because some cloze fields are easy and on the same cards others are very difficult and have a short interval and should not be retired. See picture for example, which that deck has a 180 day retiring interval and all of those notes on the same card got retired together today).

Thanks!

![image](https://user-images.githubusercontent.com/16076019/77356120-f4a46c80-6d02-11ea-98b5-99312b5e53db.png)

**Comment by LucasMIA** [comment]
What are your retirement settings? Suspend, move, tag only? Anyways tags in Anki are at the note level, so that means all cards with that note will receive the tag. Confirm if your issue is only with the tag being added or not.

**Comment by StookDog** [comment]
Just double checked and the other features appear to be working on just the notes. So I guess that's just how anki works and tags cannot be applied to individual notes. I also realized that if you want to only filter the notes that are tagged as retired and older than the retiring interval you can filter with this: "tag:"Retired" prop:ivl>x" if needed.

Thanks for clarifying!
