### ISSUE TITLE
Link to AnkiWeb

### ISSUE THREAD

**Issue by dobrosketchkun** [mass-immersion-approach/MIARetirementAddon#13]
Your link to AnkiWeb is not working dut to the duplication of ID in it: 

- Oirignal:

`2. Download the latest version of the addon from [AnkiWeb](https://ankiweb.net/shared/info/16665206551655992655).`

- Working:

`2. Download the latest version of the addon from [AnkiWeb](https://ankiweb.net/shared/info/1666520655).`

**Comment by LucasMIA** [comment]
Thanks!
