### ISSUE TITLE
Settings > Certain labels are obstructed/out of view

### ISSUE THREAD

**Issue by p2635** [mass-immersion-approach/MIARetirementAddon#4]
#### Nature of issue?

- Found a bug

#### Details about the bug: 

- Operating System: Kubuntu 18.04
- Steps to reproduce this bug: Open Retirement Add-on settings

Actual Results:
Some of the labels cannot be seen to the end.
![圖片](https://user-images.githubusercontent.com/4522927/60997683-48c31880-a34f-11e9-97e8-27597257d6c5.png)

Expected Results:
Either the font/label size/wording should be changed so it shows correctly. Alternatively, the window should be resizable so the labels can be seen when the window is made wider by the user. The new window size should probably persist so if they go on Anki again, the size should be how it was last time.

**Comment by LucasMIA** [comment]
Linux is not officially supported, if you want to open a pr to deal with this issue I would happily accept it!
